Adding PuLP library
reinvent-fiuba/RPL-2.0-runner pull request #30
Opened 2024-06-20 14:57 UTC by mbuchwald

2024-06-20 15:11 UTC, alelevinas approved these changes

2024-06-21 15:23 UTC, tutecano1995 requested changes

2024-06-21 15:23 UTC, tutecano1995 commented on requirements.txt
> +pulp~=2.8.0
Ojo que creo que este requirements.txt no es del container donde se ejecuta el código, para agregar la dependencia en el container habría que agregarla acá:

https://github.com/reinvent-fiuba/RPL-2.0-runner/blob/master/rpl_runner/Dockerfile

Que de paso, no vendría mal tener un requirements.txt para el runner

2024-06-22 20:02 UTC, mbuchwald commented on requirements.txt
> +pulp~=2.8.0
Ahh perfecto, en el PR que mande directo ya lo corrijo

2024-06-22 20:03 UTC, closed without merging